[package]
name = "hvmx-jit"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
hvmx-core = { path = "../hvmx-core" }
thiserror.workspace = true
anyhow.workspace = true
